---
title: "Plot4"
author: "Rumyana Kostova"
date: '3 11 2020 г '
output: word_document
---

##Loading data

```{r}
household_power_consumption <- read.csv("D:/Rumy/Coursera/Project1/household_power_consumption.txt", sep=";", na.strings="?")
Mydata<-subset(household_power_consumption,Date=="1/2/2007"| Date =="2/2/2007")

```

## Creating plot

```{r}
par(mfrow=c(2,2), mar=c(4,4,4,2))

plot(as.POSIXct(paste(Mydata$Date, Mydata$Time), format="%d/%m/%Y %H:%M:%S"),Mydata$Global_active_power,type = "l", xlab="Datetime",ylab="Global active power")

plot(as.POSIXct(paste(Mydata$Date, Mydata$Time), format="%d/%m/%Y %H:%M:%S"),Mydata$Voltage,type = "l", xlab="Datetime",ylab="Voltage")

matplot(as.POSIXct(paste(Mydata$Date, Mydata$Time), format="%d/%m/%Y %H:%M:%S"), cbind(Mydata$Sub_metering_1,Mydata$Sub_metering_2,Mydata$Sub_metering_3),type="l",col=c("black","red","blue"),lty=c(1,1,1), xlab="Date-time", ylab="Energy sub metering")


legend("topright",inset=0.02,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","blue","red"), lty=1, cex=0.5, box.lty=0)

plot(as.POSIXct(paste(Mydata$Date, Mydata$Time), format="%d/%m/%Y %H:%M:%S"),Mydata$Global_reactive_power,type = "l", xlab="Datetime",ylab="Global reactive power")


```

## Save as .png file

```{r}
dev.copy(png, file="Plot4.png", width = 480, height = 480)
dev.off()

```

